spring:
  application:
    name: relationship

  datasource:
    url: jdbc:mysql://localhost:3306/banking_system
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  override-with-generic-response: false
